function [ self ] = GradientBoostingRegressor( loss, ...
    learning_rate,   ...
    n_estimators, ...
    max_depth, ...
    min_samples_split, ...
    min_samples_leaf, ...
    min_weight_fraction_leaf,    ...
    subsample, ...
    max_leaf_nodes,  ...
    alpha, ...
    init, ...
    verbose, ...
    max_features,  ...
    warm_start)
self=GBM('GradientBoostingRegressor',loss, learning_rate,n_estimators,max_depth, min_samples_split,min_samples_leaf, min_weight_fraction_leaf, subsample, max_leaf_nodes,alpha,init, verbose, max_features, warm_start);
end