% Cleaning Workspace
clear all;
close all;
clc;

% Load data
load 'Data_set_seeds_indx_fixed.mat'
feature=feature(1:10,:);
target=target(1:10,:);

% The GBM
gbm=GradientBoostingClassifier('deviance', ...
    0.1,...
    5,...
    2,...
    1,...
    0.0,...
    3,...
    [],...
    1.0,...
    [],...
    0.9,...
    0,...
    [],...
    false);

% Train The Model
gbm=GBMFit(gbm,feature,target,[]);

% Predict
GBMPredict(gbm,feature(1:4,:))
Util_ravel(target(1:4,:))
